---
- name: Install Poetry on EC2 instances
  hosts: webservers
  become: yes
  tasks:
    - name: Ensure Python 3 and pip are installed
      package:
        name:
          - python3
          - python3-pip
        state: present
    - name: Ensure Poetry is installed via pip
      ansible.builtin.pip:
        name: poetry
        state: present
        executable: pip3  # Adjust pip version if necessary
        # Optionally, use `creates` to check if Poetry is already installed
        creates: /usr/local/bin/poetry  # Path to the poetry binary; adjust as needed

    - name: Add Poetry to PATH (if needed)
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$HOME/.local/bin:$PATH'
        state: present
      become_user: ec2-user
